-- definitions for fluids

--====================================================================================================
-- FLUIDS
--====================================================================================================

data:extend({
    {
        name = "ei_residual-oil",
        type = "fluid",
        icon = ei_graphics_fluid_path.."residual-oil.png",
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1000,
        fuel_value = "0.1MJ",
        base_color = { r=0.76, g=0.45, b=0.3 }, 
		flow_color = { r=0.76, g=0.45, b=0.3 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0,
        subgroup = "fluid",
        order = "a[fluid]-a[residual-oil]",
    },
    {
        name = "ei_medium-destilate",
        type = "fluid",
        icon = ei_graphics_fluid_path.."medium-destilate.png",
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1000,
        fuel_value = "0.08MJ",
        base_color = { r=0.76, g=0.45, b=0.3 }, 
		flow_color = { r=0.76, g=0.45, b=0.3 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0,
        subgroup = "fluid",
        order = "a[fluid]-a[medium-destilate]",
    },
    {
        name = "ei_heavy-destilate",
        type = "fluid",
        icon = ei_graphics_fluid_path.."heavy-destilate.png",
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1000,
        fuel_value = "0.05MJ",
        base_color = { r=0.76, g=0.45, b=0.3 }, 
		flow_color = { r=0.76, g=0.45, b=0.3 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0,
        subgroup = "fluid",
        order = "a[fluid]-a[heavy-destilate]",
    },
    {
        name = "ei_kerosene",
        type = "fluid",
        icon = ei_graphics_fluid_path.."kerosene.png",
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1000,
        fuel_value = "0.1MJ",
        base_color = { r=0.76, g=0.45, b=0.3 }, 
		flow_color = { r=0.76, g=0.45, b=0.3 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0,
        subgroup = "fluid",
        order = "a[fluid]-e[kerosene]",
    },
    {
        name = "ei_lube-destilate",
        type = "fluid",
        icon = ei_graphics_fluid_path.."lube-destilate.png",
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1000,
        base_color = { r=0.76, g=0.45, b=0.3 }, 
		flow_color = { r=0.76, g=0.45, b=0.3 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0,
        subgroup = "fluid",
        order = "a[fluid]-e[lube-destilate]",
    },
    {
        name = "ei_coal-gas",
        type = "fluid",
        icon = ei_graphics_fluid_path.."coal-gas.png",
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1000,
        gas_temperature = 15,
        fuel_value = "0.05MJ",
        base_color = { r=0.76, g=0.45, b=0.3 }, 
		flow_color = { r=0.76, g=0.45, b=0.3 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0,
        subgroup = "fluid",
        order = "b[gas]-a[coal-gas]",
    },
    {
        name = "ei_diesel",
        type = "fluid",
        icon = ei_graphics_fluid_path.."diesel.png",
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1000,
        gas_temperature = 15,
        fuel_value = "0.05MJ",
        base_color = { r=0.76, g=0.45, b=0.3 }, 
		flow_color = { r=0.76, g=0.45, b=0.3 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0,
        subgroup = "fluid",
        order = "b[fluid]-a[diesel]",
    },
    {
        name = "ei_acidic-water",
        type = "fluid",
        icon = ei_graphics_fluid_path.."acidic-water.png",
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1000,
        gas_temperature = 15,
        base_color = { r=0.76, g=0.45, b=0.3 }, 
		flow_color = { r=0.76, g=0.45, b=0.3 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0,
        subgroup = "fluid",
        order = "b[fluid]-a[acidic-water]",
    },
    {
        name = "ei_hydrofluoric-acid",
        type = "fluid",
        icon = ei_graphics_fluid_path.."hydrofluoric-acid.png",
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1000,
        gas_temperature = 15,
        base_color = { r=0.76, g=0.45, b=0.3 }, 
		flow_color = { r=0.76, g=0.45, b=0.3 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0,
        subgroup = "fluid",
        order = "b[fluid]-a[hydrofluoric-acid]",
    },
    {
        name = "ei_benzol",
        type = "fluid",
        icon = ei_graphics_fluid_path.."benzol.png",
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1000,
        gas_temperature = 15,
        base_color = { r=0.76, g=0.45, b=0.3 }, 
		flow_color = { r=0.76, g=0.45, b=0.3 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0,
        subgroup = "fluid-recipes",
        order = "b[fluid-chemistry]-c[benzol]",
    },
    {
        name = "ei_dirty-water",
        type = "fluid",
        icon = ei_graphics_fluid_path.."dirty-water.png",
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1000,
        gas_temperature = 15,
        base_color = { r=0.76, g=0.45, b=0.3 }, 
		flow_color = { r=0.76, g=0.45, b=0.3 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0,
        subgroup = "fluid-recipes",
        order = "b[fluid-chemistry]-c[dirty-water]",
    },
    {
        name = "ei_drill-fluid",
        type = "fluid",
        icon = ei_graphics_fluid_path.."drill-fluid.png",
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1000,
        gas_temperature = 15,
        fuel_value = "1MJ",
        base_color = { r=0.76, g=0.45, b=0.3 }, 
		flow_color = { r=0.76, g=0.45, b=0.3 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0,
        subgroup = "fluid-recipes",
        order = "b[fluid-chemistry]-c[drill-fluid]",
    },
    -- molten metal
    {
        name = "ei_molten-iron",
        type = "fluid",
        icon = ei_graphics_fluid_path.."molten-iron.png",
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1000,
        gas_temperature = 15,
        base_color = { r=0.76, g=0.45, b=0.3 }, 
		flow_color = { r=0.76, g=0.45, b=0.3 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0,
        subgroup = "ei_refining-molten",
        order = "a-a",
    },
    {
        name = "ei_molten-copper",
        type = "fluid",
        icon = ei_graphics_fluid_path.."molten-copper.png",
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1000,
        gas_temperature = 15,
        base_color = { r=0.76, g=0.45, b=0.3 }, 
		flow_color = { r=0.76, g=0.45, b=0.3 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0,
        subgroup = "ei_refining-molten",
        order = "a-b",
    },
    {
        name = "ei_molten-steel",
        type = "fluid",
        icon = ei_graphics_fluid_path.."molten-steel.png",
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1000,
        gas_temperature = 15,
        base_color = { r=0.76, g=0.45, b=0.3 }, 
		flow_color = { r=0.76, g=0.45, b=0.3 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0,
        subgroup = "ei_refining-molten",
        order = "a-c",
    },
    {
        name = "ei_molten-lead",
        type = "fluid",
        icon = ei_graphics_fluid_path.."molten-lead.png",
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1000,
        gas_temperature = 15,
        base_color = { r=0.76, g=0.45, b=0.3 }, 
		flow_color = { r=0.76, g=0.45, b=0.3 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0,
        subgroup = "ei_refining-molten",
        order = "a-e",
    },
    {
        name = "ei_molten-gold",
        type = "fluid",
        icon = ei_graphics_fluid_path.."molten-gold.png",
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1000,
        gas_temperature = 15,
        base_color = { r=0.76, g=0.45, b=0.3 }, 
		flow_color = { r=0.76, g=0.45, b=0.3 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0,
        subgroup = "ei_refining-molten",
        order = "a-d",
    },
    {
        name = "ei_uranium-hexafluorite",
        type = "fluid",
        icon = ei_graphics_fluid_path.."uranium-hexafluorite.png",
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1000,
        gas_temperature = 15,
        base_color = { r=0.28, g=1, b=0.6 }, 
		flow_color = { r=0.28, g=1, b=0.6 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0,
        subgroup = "fluid-recipes",
        order = "b[fluid-chemistry]-f[uranium-hexafluorite]",
    },
    {
        name = "ei_nitrogen-gas",
        type = "fluid",
        icon = ei_graphics_fluid_path.."nitrogen-gas.png",
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1000,
        gas_temperature = 15,
        base_color = { r=0.0, g=0.82, b=1 }, 
		flow_color = { r=0.0, g=0.82, b=1 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0,
        subgroup = "fluid-recipes",
        order = "b[fluid-chemistry]-f[nitrogen-gas]",
    },
    {
        name = "ei_liquid-nitrogen",
        type = "fluid",
        icon = ei_graphics_fluid_path.."liquid-nitrogen.png",
        icon_size = 64,
        fuel_value = "1MJ",
        default_temperature = 15,
        max_temperature = 1000,
        gas_temperature = 15,
        base_color = { r=0.0, g=0.82, b=1 }, 
		flow_color = { r=0.0, g=0.82, b=1 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0,
        subgroup = "fluid-recipes",
        order = "b[fluid-chemistry]-f[liquid-nitrogen]",
    },
    {
        name = "ei_computing-power",
        type = "fluid",
        icon = ei_graphics_fluid_path.."computing-power.png",
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1000,
        gas_temperature = 15,
        base_color = { r=0.0, g=0.82, b=1 }, 
		flow_color = { r=0.0, g=0.82, b=1 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0,
        subgroup = "ei_refining-tech",
        order = "a-a-a",
    },
})