-- definitions for fluids

--====================================================================================================
-- FLUIDS
--====================================================================================================

data:extend({
    {
        name = "ei_residual-oil",
        type = "fluid",
        icon = ei_graphics_fluid_path.."residual-oil.png",
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1000,
        fuel_value = "0.1MJ",
        base_color = { r=0.76, g=0.45, b=0.3 }, 
		flow_color = { r=0.76, g=0.45, b=0.3 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0,
        subgroup = "fluid",
        order = "a[fluid]-a[residual-oil]",
    },
    {
        name = "ei_medium-destilate",
        type = "fluid",
        icon = ei_graphics_fluid_path.."medium-destilate.png",
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1000,
        fuel_value = "0.08MJ",
        base_color = { r=0.76, g=0.45, b=0.3 }, 
		flow_color = { r=0.76, g=0.45, b=0.3 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0,
        subgroup = "fluid",
        order = "a[fluid]-a[medium-destilate]",
    },
    {
        name = "ei_heavy-destilate",
        type = "fluid",
        icon = ei_graphics_fluid_path.."heavy-destilate.png",
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1000,
        fuel_value = "0.05MJ",
        base_color = { r=0.76, g=0.45, b=0.3 }, 
		flow_color = { r=0.76, g=0.45, b=0.3 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0,
        subgroup = "fluid",
        order = "a[fluid]-a[heavy-destilate]",
    },
    {
        name = "ei_kerosene",
        type = "fluid",
        icon = ei_graphics_fluid_path.."kerosene.png",
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1000,
        fuel_value = "0.1MJ",
        base_color = { r=0.76, g=0.45, b=0.3 }, 
		flow_color = { r=0.76, g=0.45, b=0.3 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0,
        subgroup = "fluid",
        order = "a[fluid]-e[kerosene]",
    },
    {
        name = "ei_lube-destilate",
        type = "fluid",
        icon = ei_graphics_fluid_path.."lube-destilate.png",
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1000,
        base_color = { r=0.76, g=0.45, b=0.3 }, 
		flow_color = { r=0.76, g=0.45, b=0.3 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0,
        subgroup = "fluid",
        order = "a[fluid]-e[lube-destilate]",
    },
    {
        name = "ei_coal-gas",
        type = "fluid",
        icon = ei_graphics_fluid_path.."coal-gas.png",
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1000,
        gas_temperature = 15,
        fuel_value = "0.05MJ",
        base_color = { r=0.76, g=0.45, b=0.3 }, 
		flow_color = { r=0.76, g=0.45, b=0.3 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0,
        subgroup = "fluid",
        order = "b[gas]-a[coal-gas]",
    },
    {
        name = "ei_diesel",
        type = "fluid",
        icon = ei_graphics_fluid_path.."diesel.png",
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1000,
        gas_temperature = 15,
        fuel_value = "0.05MJ",
        base_color = { r=0.76, g=0.45, b=0.3 }, 
		flow_color = { r=0.76, g=0.45, b=0.3 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0,
        subgroup = "fluid",
        order = "b[fluid]-a[diesel]",
    },
    {
        name = "ei_acidic-water",
        type = "fluid",
        icon = ei_graphics_fluid_path.."acidic-water.png",
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1000,
        gas_temperature = 15,
        base_color = { r=0.76, g=0.45, b=0.3 }, 
		flow_color = { r=0.76, g=0.45, b=0.3 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0,
        subgroup = "fluid",
        order = "b[fluid]-a[acidic-water]",
    },
    {
        name = "ei_hydrofluoric-acid",
        type = "fluid",
        icon = ei_graphics_fluid_path.."hydrofluoric-acid.png",
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1000,
        gas_temperature = 15,
        base_color = { r=0.76, g=0.45, b=0.3 }, 
		flow_color = { r=0.76, g=0.45, b=0.3 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0,
        subgroup = "fluid",
        order = "b[fluid]-a[hydrofluoric-acid]",
    },
    {
        name = "ei_benzol",
        type = "fluid",
        icon = ei_graphics_fluid_path.."benzol.png",
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1000,
        gas_temperature = 15,
        base_color = { r=0.76, g=0.45, b=0.3 }, 
		flow_color = { r=0.76, g=0.45, b=0.3 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0,
        subgroup = "fluid-recipes",
        order = "b[fluid-chemistry]-c[benzol]",
    },
    {
        name = "ei_dirty-water",
        type = "fluid",
        icon = ei_graphics_fluid_path.."dirty-water.png",
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1000,
        gas_temperature = 15,
        base_color = { r=0.76, g=0.45, b=0.3 }, 
		flow_color = { r=0.76, g=0.45, b=0.3 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0,
        subgroup = "fluid-recipes",
        order = "b[fluid-chemistry]-c[dirty-water]",
    },
    {
        name = "ei_drill-fluid",
        type = "fluid",
        icon = ei_graphics_fluid_path.."drill-fluid.png",
        icon_size = 64,
        default_temperature = 15,
        max_temperature = 1000,
        gas_temperature = 15,
        fuel_value = "1MJ",
        base_color = { r=0.76, g=0.45, b=0.3 }, 
		flow_color = { r=0.76, g=0.45, b=0.3 }, 
		pressure_to_speed_ratio = 0.400, 
		flow_to_energy_ratio = 0,
        subgroup = "fluid-recipes",
        order = "b[fluid-chemistry]-c[drill-fluid]",
    },
})