data:extend({
    {
        name = "ei_plasma-cube-logo",
        type = "sprite",
        filename = ei_graphics_path.."graphics/128_placeholder.png",
        size = 128,
    },
    {
        name = "ei_age_progression",
        type = "sprite",
        filename = ei_graphics_other_path.."age_progression.png",
        width = 384,
        height = 256,
    },
    {
        name = "ei_uranium_patch",
        type = "sprite",
        filename = ei_graphics_entity_path.."uranium-patch.png",
        width = 567,
        height = 565,
    },
    {
        name = "ei_artifact",
        type = "sprite",
        filename = ei_graphics_entity_path.."alien-beacon_off-2.png",
        width = 512,
        height = 512,
    },
    {
        name = "ei_train_progression",
        type = "sprite",
        filename = ei_graphics_other_path.."train_progression.png",
        width = 820,
        height = 410,
    },
    {
        name = "ei_robots",
        type = "sprite",
        filename = ei_graphics_other_path.."robots.png",
        width = 1166,
        height = 716,
    },
    {
        name = "ei_beacons",
        type = "sprite",
        filename = ei_graphics_other_path.."beacons.png",
        width = 981,
        height = 835,
    },
    {
        name = "ei_pipes",
        type = "sprite",
        filename = ei_graphics_path.."graphics/data-pipes/pipe-straight-vertical-single.png",
        width = 160,
        height = 160,
    },
    {
        name = "ei_space_destinations",
        type = "sprite",
        filename = ei_graphics_tech_path.."black-hole-exploration.png",
        width = 256,
        height = 256,
    },
    {
        name = "ei_induction_matrix",
        type = "sprite",
        filename = ei_graphics_tech_path.."induction-matrix-core.png",
        width = 256,
        height = 256,
    },
    {
        name = "ei_exotic_stabilizers",
        type = "sprite",
        filename = ei_graphics_entity_path.."alien-stabilizer.png",
        width = 512,
        height = 512,
    },
    {
        name = "ei_fission_reactors",
        type = "sprite",
        filename = ei_graphics_entity_path.."high-temperature-reactor.png",
        width = 512,
        height = 512,
    },
    {
        name = "ei_fusion_power",
        type = "sprite",
        filename = ei_graphics_other_path.."fusion.png",
        width = 1108,
        height = 794,
    },

})