data:extend({
    {
        name = "ei_plasma-cube-logo",
        type = "sprite",
        filename = ei_graphics_path.."graphics/128_placeholder.png",
        size = 128,
    },
    {
        name = "ei_age_progression",
        type = "sprite",
        filename = ei_graphics_other_path.."age_progression.png",
        width = 384,
        height = 256,
    },
    {
        name = "ei_uranium_patch",
        type = "sprite",
        filename = ei_graphics_entity_path.."uranium-patch.png",
        width = 567,
        height = 565,
    },
    {
        name = "ei_artifact",
        type = "sprite",
        filename = ei_graphics_entity_path.."alien-beacon_off-2.png",
        width = 512,
        height = 512,
    },
    {
        name = "ei_train_progression",
        type = "sprite",
        filename = ei_graphics_other_path.."train_progression.png",
        width = 820,
        height = 410,
    },
    {
        name = "ei_robots",
        type = "sprite",
        filename = ei_graphics_other_path.."robots.png",
        width = 1166,
        height = 716,
        scale = 0.75,
    },
    {
        name = "ei_beacons",
        type = "sprite",
        filename = ei_graphics_other_path.."beacons.png",
        width = 981,
        height = 835,
        scale = 0.75,
    },
    {
        name = "ei_pipes",
        type = "sprite",
        filename = ei_graphics_path.."graphics/data-pipes/pipe-straight-vertical-single.png",
        width = 160,
        height = 160,
    },
    {
        name = "ei_space_destinations",
        type = "sprite",
        filename = ei_graphics_tech_path.."black-hole-exploration.png",
        width = 256,
        height = 256,
    },
    {
        name = "ei_induction_matrix",
        type = "sprite",
        filename = ei_graphics_tech_path.."induction-matrix-core.png",
        width = 256,
        height = 256,
    },
    {
        name = "ei_exotic_stabilizers",
        type = "sprite",
        filename = ei_graphics_entity_path.."alien-stabilizer.png",
        width = 512,
        height = 512,
    },
    {
        name = "ei_fission_reactors",
        type = "sprite",
        filename = ei_graphics_entity_path.."high-temperature-reactor.png",
        width = 512,
        height = 512,
    },
    {
        name = "ei_fusion_power",
        type = "sprite",
        filename = ei_graphics_other_path.."fusion.png",
        width = 1108,
        height = 794,
        scale = 0.75,
    },
    {
        name = "ei_black_hole",
        type = "sprite",
        filename = ei_graphics_tech_path.."black-hole.png",
        width = 256,
        height = 256,
    },
    {
        name = "ei_compilatron",
        type = "sprite",
        filename = ei_graphics_other_path.."compilatron.png",
        width = 64,
        height = 64,
    },
    {
        name = "ei_lab",
        type = "sprite",
        filename = ei_graphics_other_path.."lab.png",
        width = 64,
        height = 64,
    },
    {
        name = "ei_rocket-silo",
        type = "sprite",
        filename = ei_graphics_other_path.."rocket-silo.png",
        width = 64,
        height = 64,
    },
    {
        name = "ei_knowledge-console",
        type = "sprite",
        filename = ei_graphics_entity_2_path.."knowledge-console.png",
        width = 256,
        height = 256,
    },

    -- Knowledge system
    {
        name = "ei_part",
        type = "sprite",
        filename = ei_graphics_other_path.."schematic.png",
        width = 128,
        height = 128,
    },
    {
        name = "ei_schematic",
        type = "sprite",
        filename = ei_graphics_other_path.."blueprint.png",
        width = 128,
        height = 128,
    },
    {
        name = "ei_knowledge-gate",
        type = "sprite",
        filename = ei_graphics_tech_2_path.."gate.png",
        width = 256,
        height = 256,
        scale = 0.5,
    },
    {
        name = "ei_knowledge-crystal-accumulator",
        type = "sprite",
        filename = ei_graphics_tech_2_path.."crystal-accumulator.png",
        width = 256,
        height = 256,
        scale = 0.5,
    },
    {
        name = "ei_knowledge-crystal-accumulator-repair",
        type = "sprite",
        filename = ei_graphics_tech_2_path.."crystal-accumulator-repair.png",
        width = 256,
        height = 256,
        scale = 0.5,
    },
    {
        name = "ei_knowledge-bio-chamber",
        type = "sprite",
        filename = ei_graphics_tech_path.."bio-chamber.png",
        width = 256,
        height = 256,
        scale = 0.5,
    },
    {
        name = "ei_knowledge-bio_insulated-wire",
        type = "sprite",
        filename = ei_graphics_other_path.."bio_insulated-wire.png",
        width = 64,
        height = 64,
        scale = 2,
    },
    {
        name = "ei_knowledge-bio_energy-crystal",
        type = "sprite",
        filename = ei_graphics_other_path.."bio_energy-crystal.png",
        width = 64,
        height = 64,
        scale = 2,
    },
    {
        name = "ei_knowledge-bio_high-energy-crystal",
        type = "sprite",
        filename = ei_graphics_other_path.."bio_high-energy-crystal.png",
        width = 64,
        height = 64,
        scale = 2,
    },
    {
        name = "ei_knowledge-bio_hydrofluoric-acid",
        type = "sprite",
        filename = ei_graphics_other_path.."bio_hydrofluoric-acid.png",
        width = 64,
        height = 64,
        scale = 2,
    },
    {
        name = "ei_knowledge-bio_nitric-acid",
        type = "sprite",
        filename = ei_graphics_other_path.."bio_nitric-acid.png",
        width = 64,
        height = 64,
        scale = 2,
    },
    {
        name = "ei_knowledge-bio_electronic-parts",
        type = "sprite",
        filename = ei_graphics_other_path.."bio_electronic-parts.png",
        width = 64,
        height = 64,
        scale = 2,
    },

})